### ISSUE TITLE
一键快速安装部署，执行run.sh报错

### ISSUE THREAD

**Issue by susengo** [bcosorg/bcos#110]
执行一键快速安装部署，执行run.sh报错如下，请教为何会出现这个错误，万分感谢
-------------------------------------------------------------------------------
开始检查配置...
配置检查成功!!!
module.js:549
    throw err;
    ^

Error: Cannot find module 'secp256k1'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/go/src/github.com/bcos/tool/utils.js:1:81)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
管理员账户生成失败!!!
chmod: cannot access ‘/bcos-data/node0/start0.sh’: No such file or directory
chmod: cannot access ‘/bcos-data/node1/start1.sh’: No such file or directory
[root@localhost sample]# sh: /bcos-data/node1/start1.sh: No such file or directory
sh: /bcos-data/node0/start0.sh: No such file or directory

**Comment by susengo** [comment]
我是全局安装了'secp256k1'

**Comment by zbj741** [comment]
2楼的方法我试过了，还是不行

**Comment by lilianwen** [comment]
我也遇到这个问题，后来我尝试了一下再一次执行之前的build.sh，然后执行后面的run.sh，结果就OK了。
