### ISSUE TITLE
cd systemcontractv2/ babel-node deploy.js 报错

### ISSUE THREAD

**Issue by luotianwen** [bcosorg/bcos#12]
[root@localhost bcos]# cd systemcontractv2/
[root@localhost systemcontractv2]# babel-node deploy.js

/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
throw e;
^
Error: Couldn't find preset "es2017" relative to directory "/home/bcos/systemcontractv2"
at /usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
at Array.map (native)
at OptionManager.resolvePresets (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
at OptionManager.mergePresets (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
at OptionManager.mergeOptions (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
at OptionManager.init (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
at compile (/usr/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:103:45)
at loader (/usr/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:14)
at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
at Module.load (module.js:356:32)

**Comment by toxotguo** [comment]
1）请在tool目录下执行以下命令，安装相关依赖模块
npm install
2) 再执行
babel-node deploy.js

**Comment by luotianwen** [comment]
npm install
npm WARN package.json systemcontract@1.0.0 No repository field.
[root@localhost systemcontractv2]# babel-node deploy.js 

/home/bcos/systemcontractv2/deploy.js:28
_asyncToGenerator(function* () {
                          ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at loader (/usr/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at Object.<anonymous> (/usr/lib/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by toxotguo** [comment]
@luotianwen 
从输出来看，是网络原因依赖没安装成功，请按下面重试一下
sudo npm install -g cnpm --registry=https://registry.npm.taobao.org
cnpm install

再执行 
babel-node deploy.js

**Comment by luotianwen** [comment]
# cnpm install

/usr/lib/node_modules/cnpm/bin/cnpm:5
const debug = require('debug')('cnpm');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

**Comment by luotianwen** [comment]
[root@localhost systemcontractv2]# cnpm install

/usr/lib/node_modules/cnpm/bin/cnpm:5
const debug = require('debug')('cnpm');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

**Comment by toxotguo** [comment]
sudo npm install -g cnpm --registry=https://registry.npm.taobao.org
sudo cnpm install -g babel-cli babel-preset-es2017
echo '{ "presets": ["es2017"] }' > ~/.babelrc
再执行
cnpm install

@luotianwen

**Comment by luotianwen** [comment]
是在systemcontractv2这个目录下吗

**Comment by toxotguo** [comment]
@luotianwen 是的

**Comment by toxotguo** [comment]
@luotianwen
使用说明文档已更新
请参考https://github.com/bcosorg/bcos/blob/master/doc/manual/manual.md

**Comment by cristicmf** [comment]
- 检查一下node和镜像cnpm，是否都正常安装
- 在bcos/systemcontractv2/,安装项目依赖包，cnpm install/npm install
- 部署合约 babel-node deploy.js

**Comment by cristicmf** [comment]
@luotianwen

**Comment by luotianwen** [comment]
好 重新安装 再试一试

**Comment by luotianwen** [comment]
还是不行  ERROR|2017-08-07 11:29:41|Client not ready or cannot find the system contract !
ERROR|2017-08-07 11:29:41|check service enable state failed ! nodeid : a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da
ERROR|2017-08-07 11:29:46|Client not ready or cannot find the system contract !
ERROR|2017-08-07 11:29:46|*** listGroupFileInfo failed ***

**Comment by cristicmf** [comment]
这个跟部署的node环境没有关系了。

**Comment by toxotguo** [comment]
@luotianwen 
这个错误不影响区块链的正常运行。
可以参看这个issues的信息
https://github.com/bcosorg/bcos/issues/8
