### ISSUE TITLE
docker多实例部署问题

### ISSUE THREAD

**Issue by cherry-wb** [bcosorg/bcos#69]
您好，我按照https://github.com/bcosorg/bcos/blob/master/docker/README.md的说明在docker中部署BCOS，但是在执行到第二步就卡住了，求解答，谢谢！
我的系统是ubuntu 16.04，已经执行build.sh中的步骤
执行2.1 配置系统合约出错
$ cd bcos/systemcontractv2
$ babel-node deploy.js
出错信息如下：
RPC=http://127.0.0.1:35500
Ouputpath=./output/
/home/wb/bcos/systemcontractv2/web3sync.js:64
let getBlockNumber = (() => {
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at loader (/usr/local/lib/node_modules/babel-cli/node_modules/_babel-register@6.26.0@babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/_babel-register@6.26.0@babel-register/lib/node.js:154:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/wb/bcos/sys

**Comment by cherry-wb** [comment]
手动安装最新版本nodejs后即可解决问题。
https://nodejs.org/zh-cn/download/
