### ISSUE TITLE
单节点跑报错，不知道是哪里没配置好？

### ISSUE THREAD

**Issue by alex1226** [bcosorg/bcos#8]
ERROR|2017-08-03 11:10:03|Client not ready or cannot find the system contract !
ERROR|2017-08-03 11:10:03|check service enable state failed ! nodeid : de0fa385816b505799433e54b88788e21cb42092a6ff5bcaa2285d7ace906e5e6ce8ef2b30134ff276a5834d58721291acc5864e07e6d52469b79b28e699dfde
ERROR|2017-08-03 11:10:08|Client not ready or cannot find the system contract !
ERROR|2017-08-03 11:10:08|*** listGroupFileInfo failed ***

**Comment by JUZIX-DEV** [comment]
系统合约部署没有将FileInfoManager.sol部署及注册进去。需要运行这个脚本部署系统合约， https://github.com/bcosorg/bcos/blob/master/systemcontractv2/deploy.js， 
命令： 
cd systemcontractv2
babel-node deploy.js

**Comment by alex1226** [comment]
还是没成功，感觉没有ethereum那套上手快。从中小公司来看，要想做大生态平台，为何不搞简单点清晰点，至少要很容易挖矿和跑合约。投入时间有限，面对很多平台开发项目，只有让人很快看到东西跑得起来有效果和正常结果了，觉得好像没多少坑了，才决定是不是要跟进。

**Comment by JUZIX-DEV** [comment]
你这个Dfs服务没有启动起来， 并不会影响挖矿和跑合约的。 另外dfs节点配置某人是无法跑起来的， 需要通过java sdk添加Dfs服务节点激活才能运行起来。 默认dfs服务是关闭的。

**Comment by luotianwen** [comment]
babel-node deploy.js 执行这个报错   babel-node deploy.js 

/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
              ^
Error: Couldn't find preset "es2017" relative to directory "/home/bcos/systemcontractv2"
    at /usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/usr/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:103:45)
    at loader (/usr/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:356:32)

**Comment by luotianwen** [comment]
INFO|2017-08-07 14:19:58|Init PBFTClient success
INFO|2017-08-07 14:20:00|⧎ ℹ|⧎ ℹ  02:20:00 PM.050|p2p  Listen address set to Public address: 192.168.10.67 . UPnP disabled.
TRACE|2017-08-07 14:20:00|NodeTable::addNode a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da,1
TRACE|2017-08-07 14:20:00|NodeTable::noteActiveNode a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da,192.168.10.67:30303
TRACE|2017-08-07 14:20:00|NodeConnParamsManager::connNodeenode://a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da@192.168.10.67:30303 Valid=1
TRACE|2017-08-07 14:20:00|NodeConnParamsManager::connNode startenode://a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da@192.168.10.67:30303 Valid=1
TRACE|2017-08-07 14:20:00|WebThreeDirect::addPeer 
TRACE|2017-08-07 14:20:00|Host::addPeerenode://a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da@192.168.10.67:30303
TRACE|2017-08-07 14:20:00|Host::addPeer Required
TRACE|2017-08-07 14:20:00|Host::requirePeera57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da
TRACE|2017-08-07 14:20:00|NodeTable::addNode a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da,1
TRACE|2017-08-07 14:20:00|NodeTable::noteActiveNode a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da,192.168.10.67:30303
DEBUG|2017-08-07 14:20:00|****#### hey, init the fileserver! base: /home/bcos/mydata/nodedata-1/data//filestorage group: group1 node: a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da
DEBUG|2017-08-07 14:20:00|##@@@ init_storage ###
DEBUG|2017-08-07 14:20:00|####  create directory for container_id: files

DEBUG|2017-08-07 14:20:00|####  create directory for container_id: files,  full directory: /home/bcos/mydata/nodedata-1/data//filestorage/45/00/files
ERROR|2017-08-07 14:20:00|Client not ready or cannot find the system contract !
ERROR|2017-08-07 14:20:00|Client not ready or cannot find the system contract !
DEBUG|2017-08-07 14:20:00|getGroupPageCount failed !
ERROR|2017-08-07 14:20:00|*** listGroupFileInfo failed ***

DEBUG|2017-08-07 14:20:00|*****#### the local fs has: 0files

DEBUG|2017-08-07 14:20:00|****** getLocalFileInfos done, total=0

DEBUG|2017-08-07 14:20:00|the file info sanner is started... running

DEBUG|2017-08-07 14:20:00|init state is OK, start real file working !!
ERROR|2017-08-07 14:20:00|Client not ready or cannot find the system contract !
ERROR|2017-08-07 14:20:00|check service enable state failed ! nodeid : a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da
ERROR|2017-08-07 14:20:00|the file service of node: a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074dais not open !
ERROR|2017-08-07 14:20:00|Client not ready or cannot find the system contract !
ERROR|2017-08-07 14:20:00|check service enable state failed ! nodeid : a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da
DEBUG|2017-08-07 14:20:00|DfsFileInfoScanner (file sync module) has been inited !

TRACE|2017-08-07 14:20:00|*****#### HTTP start ###******
TRACE|2017-08-07 14:20:00|JSONRPC Admin Session Key: jxCRtdUs0Ww=
ERROR|2017-08-07 14:20:00|resetConfig: can't find myself id, stop sealing
INFO|2017-08-07 14:20:00|^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Report: blk=0,hash=b29f87e5…,idx=0, Next: blk=1
ERROR|2017-08-07 14:20:00|resetConfig: can't find myself id, stop sealing
TRACE|2017-08-07 14:20:00|Client Mining Beneficiary: 0000000000000000000000000000000000000000
INFO|2017-08-07 14:20:03|Ready to broadcastViewChangeReq, blk=0,to_view=1, give up for not miner
TRACE|2017-08-07 14:20:03|checkTimeout timecost=0.000353
ERROR|2017-08-07 14:20:05|Client not ready or cannot find the system contract !
DEBUG|2017-08-07 14:20:05|getGroupPageCount failed !
ERROR|2017-08-07 14:20:05|*** listGroupFileInfo failed ***

**Comment by luotianwen** [comment]
日志里面报错啊

**Comment by luotianwen** [comment]
ERROR|2017-08-07 14:46:08|resetConfig: can't find myself id, stop sealing
INFO|2017-08-07 14:46:08|PBFT initEnv success
ERROR|2017-08-07 14:46:08|resetConfig: can't find myself id, stop sealing
INFO|2017-08-07 14:46:08|^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Report: blk=0,hash=b29f87e5…,idx=0, Next: blk=1
INFO|2017-08-07 14:46:08|Init PBFTClient success
INFO|2017-08-07 14:46:09|⧎ ℹ|⧎ ℹ  02:46:09 PM.763|p2p  Listen address set to Public address: 192.168.10.67 . UPnP disabled.
TRACE|2017-08-07 14:46:09|NodeConnParamsManager::connNodeenode://a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da@192.168.10.67:30303 Valid=1
TRACE|2017-08-07 14:46:09|NodeConnParamsManager::connNode startenode://a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da@192.168.10.67:30303 Valid=1
TRACE|2017-08-07 14:46:09|WebThreeDirect::addPeer 
TRACE|2017-08-07 14:46:09|Host::addPeerenode://a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da@192.168.10.67:30303
TRACE|2017-08-07 14:46:09|Host::addPeer Required
TRACE|2017-08-07 14:46:09|Host::requirePeera57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da
TRACE|2017-08-07 14:46:09|NodeTable::addNode a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da,1
TRACE|2017-08-07 14:46:09|NodeTable::noteActiveNode a57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da,192.168.10.67:30303
DEBUG|2017-08-07 14:46:09|****#### hey, init the fileserver! base: /home/bcos/mydata/nodedata-1/data//filestorage group: group1 node: b57c95ab42582551319edbf374630de7f6ab13e744b702ba9d3b7ae1c77103902065f867d600b9fbbcceae9ffcde1e8fca0da9fb1cf59f4fa9c9fa2b363074da
DEBUG|2017-08-07 14:46:09|##@@@ init_storage ###
DEBUG|2017-08-07 14:46:09|####  create directory for container_id: files

DEBUG|2017-08-07 14:46:09|####  create directory for container_id: files,  full directory: /home/bcos/mydata/nodedata-1/data//filestorage/45/00/files
DEBUG|2017-08-07 14:46:09|create first storage files directory: /home/bcos/mydata/nodedata-1/data//filestorage/45
DEBUG|2017-08-07 14:46:09|create second storage files directory: /home/bcos/mydata/nodedata-1/data//filestorage/45/00
DEBUG|2017-08-07 14:46:09|create storage files directory: /home/bcos/mydata/nodedata-1/data//filestorage/45/00/files
ERROR|2017-08-07 14:46:09|Client not ready or cannot find the system contract !
ERROR|2017-08-07 14:46:09|Client not ready or cannot find the system contract !
DEBUG|2017-08-07 14:46:09|getGroupPageCount failed !
ERROR|2017-08-07 14:46:09|*** listGroupFileInfo failed ***

**Comment by toxotguo** [comment]
@luotianwen 
请参看上面 @JUZIX-DEV 的回复
dfs的错误信息并不影响bcoseth节点的运行，只有能部署合约和发交易，区块链网络既是正常的。
dfs特性的使用请参看使用说明书来配置。
