### ISSUE TITLE
Error: Cannot find module 'secp256k1'

### ISSUE THREAD

**Issue by luotianwen** [bcosorg/bcos#9]
[root@localhost bcos]# cd tool/
[root@localhost tool]# node accountManager.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'secp256k1'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/bcos/tool/utils.js:1:81)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
[root@localhost tool]# node accountManager.js

**Comment by luotianwen** [comment]
There are unfinished transactions remaining. You might consider running yum-complete-transaction, or "yum-complete-transaction --cleanup-only" and "yum history redo last", first to finish them. If those don't work you'll have to try removing/installing packages by hand (maybe package-cleanup can help).

**Comment by luotianwen** [comment]
[root@localhost bcos]# chmod +x scripts/install_deps.sh
[root@localhost bcos]# ./scripts/install_deps.sh
Installing cpp-ethereum dependencies on CentOS.
There are unfinished transactions remaining. You might consider running yum-complete-transaction, or "yum-complete-transaction --cleanup-only" and "yum history redo last", first to finish them. If those don't work you'll have to try removing/installing packages by hand (maybe package-cleanup can help).

**Comment by luotianwen** [comment]
有没有问题

**Comment by toxotguo** [comment]
1）请在tool目录下执行以下命令，安装相关依赖模块
 npm install 
2）再执行
node accountManager.js

**Comment by luotianwen** [comment]
嗯 可以了

**Comment by luotianwen** [comment]
./build/eth/eth --genesis ./genesis.json --config ./config.json &
2017-08-04 10:01:55,679 DEBUG [default] [root@localhost.localdomain] [int dev::rpc::fs::DfsFileInfoScanner::getContractFileInfos(std::map<std::basic_string<char>, dev::rpc::fs::DfsFileInfo>&)] [/home/bcos/libweb3jsonrpc/dfs/DfsFileInfoScanner.cpp:251] Logger [fileLogger] is not registered yet!
2017-08-04 10:01:55,679 ERROR [default] Client not ready or cannot find the system contract !
2017-08-04 10:01:55,679 DEBUG [default] [root@localhost.localdomain] [void dev::rpc::fs::updateFileContracts()] [/home/bcos/libweb3jsonrpc/dfs/DfsContractCaller.cpp:32] Logger [fileLogger] is not registered yet!
2017-08-04 10:01:55,679 ERROR [default] check service enable state failed ! nodeid : 1cb666be53d1be36634430bf91c6e3d555951ac079fcbdd7adf54a7b7bdcb6eafcf75f931500a187eed0d6687cba941032517a39d4cd1a3bc602d2e3f1bf15bd
2017-08-04 10:01:55,680 DEBUG [default] [root@localhost.localdomain] [bool dev::rpc::fs::DfsFileServer::checkServiceAvailable()] [/home/bcos/libweb3jsonrpc/dfs/DfsFileServer.cpp:297] Logger [fileLogger] is not registered yet!
2017-08-04 10:02:00,462 TRACE [default] [void dev::eth::Client::tick()] [/home/bcos/libethereum/Client.cpp:844] Since 2017-08-04 02:01:45.394Z (15): 15ticks
2017-08-04 10:02:00,462 DEBUG [default] [root@localhost.localdomain] [void dev::eth::Client::tick()] [/home/bcos/libethereum/Client.cpp:844] Logger [fileLogger] is not registered yet!
2017-08-04 10:02:00,692 ERROR [default] Client not ready or cannot find the system contract !
2017-08-04 10:02:00,692 DEBUG [default] [root@localhost.localdomain] [void dev::rpc::fs::updateFileContracts()] [/home/bcos/libweb3jsonrpc/dfs/DfsContractCaller.cpp:32] Logger [fileLogger] is not registered yet!
2017-08-04 10:02:00,692 DEBUG [default] [root@localhost.localdomain] [int dev::rpc::fs::DfsFileInfoScanner::queryGroupFileInfo(const string&, std::vector<std::basic_string<char> >&)] [/home/bcos/libweb3jsonrpc/dfs/DfsFileInfoScanner.cpp:227] getGroupPageCount failed !
2017-08-04 10:02:00,692 DEBUG [default] [root@localhost.localdomain] [int dev::rpc::fs::DfsFileInfoScanner::queryGroupFileInfo(const string&, std::vector<std::basic_string<char> >&)] [/home/bcos/libweb3jsonrpc/dfs/DfsFileInfoScanner.cpp:227] Logger [fileLogger] is not registered yet!
2017-08-04 10:02:00,692 ERROR [default] *** listGroupFileInfo failed ***

**Comment by luotianwen** [comment]
最后一步报错了

**Comment by luotianwen** [comment]
找到了  genesis.json  config.json里面的配置问题 教程不是很明确

**Comment by toxotguo** [comment]
请参考这个问题的回复
https://github.com/bcosorg/bcos/issues/8

**Comment by luotianwen** [comment]
怎么重启节点

**Comment by luotianwen** [comment]
[root@localhost bcos]# cd systemcontractv2/
[root@localhost systemcontractv2]# babel-node deploy.js 

/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
              ^
Error: Couldn't find preset "es2017" relative to directory "/home/bcos/systemcontractv2"
    at /usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/usr/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:103:45)
    at loader (/usr/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:356:32)

**Comment by luotianwen** [comment]
@toxotguo 部署合约报错
